---
title: "Main Code"
author: "Elias Benjamin Farr, Lisa Marie Milchsack"
date: "17 Mai 2019"
output: html_document
---
#installation of required packages
```{r install ggplot2}
# requires installation of latest Rtool version
# install package ggplot2
install.packages("ggplot2")
# load package
library("ggplot2")

#required packages for selection of DV and SSTs
install.packages("tidyverse")
install.packages("factoextra")
install.packages("data.table")
library(tidyverse)
library(cluster)
library(factoextra)
library(data.table)
```

#data clean up
```{r}
#finding all breast cancer cell lines
BCCL_Numbers <- which(allDepMapData$annotation[4]== "Breast Cancer")
BCCL_Annotation <- subset(allDepMapData$annotation, Primary.Disease == "Breast Cancer")
#see what we got
summary(BCCL_Annotation)
# copy expression matrix to new dataframes
df1 <- allDepMapData$expression
df2 <- allDepMapData$copynumber
df3 <- allDepMapData$kd.ceres
df4 <- allDepMapData$kd.prob
#change column names to numbers for easier handling
names(df1) <- c(1:544)
names(df2) <- c(1:544)
names(df3) <- c(1:544)
names(df4) <- c(1:544)
#extract BCCL as dataframe
BCCL_Expression <- as.data.frame( df1[, c(BCCL_Numbers)])
BCCl_Copynumber <- as.data.frame( df2[, c(BCCL_Numbers)])
BCCL_kd.ceres <- as.data.frame( df3[, c(BCCL_Numbers)])
BCCL_kd.prob <- as.data.frame( df4[, c(BCCL_Numbers)])
dim(BCCL_Expression)
dim(BCCl_Copynumber)
dim(BCCL_kd.ceres)
dim(BCCL_kd.prob)
#reorder rows alphabetically
BCCL_Expression <- BCCL_Expression[order(rownames(BCCL_Expression)), ]
BCCl_Copynumber <- BCCl_Copynumber[order(rownames(BCCl_Copynumber)), ]
BCCL_kd.ceres <- BCCL_kd.ceres[order(rownames(BCCL_kd.ceres)), ]
BCCL_kd.prob <- BCCL_kd.prob[order(rownames(BCCL_kd.prob)), ]
#subset Mutation matrix in BCCL
BCCL_Mutation <- allDepMapData$mutation[c(BCCL_Numbers)]
```

```{r} 
Patients_ID <- BCCL_Annotation[1] #get patients ID from annotation matrix
tPatients_ID <- t(Patients_ID) #transpose Patients_ID because it was a column and we want to insert it as row
rownameskdc <- rownames(BCCL_kd.ceres) # save old rownames
existingDF <- BCCL_kd.ceres  # define variables for BCCL_kd.ceres
r <- 1
newrow <- tPatients_ID
#defining a function we can use more often to insert rows
insertRow <- function(existingDF, newrow, r) { 
    existingDF[seq(r+1,nrow(existingDF)+1),] <- existingDF[seq(r,nrow(existingDF)),]
    existingDF[r,] <- newrow
    existingDF
}
BCCL_kd.ceres_ID <- insertRow(existingDF, newrow, r)
rownames(BCCL_kd.ceres_ID) <- c("Deep_ID", rownameskdc) # change rownames back 
BCCL_kd.ceres_ID[1:2, ]
#do the same with other 3 dataframes
rownamesex <- rownames(BCCL_Expression) #save rownames
existingDF <- BCCL_Expression  # define variables for BCCL_Erpression
r <- 1
newrow <- tPatients_ID
BCCL_Expression_ID <- insertRow(existingDF, newrow, r)
rownames(BCCL_Expression_ID) <- c("Deep_ID", rownamesex)
rownamescn <- rownames(BCCl_Copynumber) #save rownames
existingDF <- BCCl_Copynumber  # define variables for BCCL_Copynumber
r <- 1
newrow <- tPatients_ID
BCCl_Copynumber_ID <- insertRow(existingDF, newrow, r)
rownames(BCCl_Copynumber_ID) <- c("Deep_ID", rownamescn)
rownameskdp <- rownames(BCCL_kd.prob) #save rownames
existingDF <- BCCL_kd.prob  # define variables for BCCL_kd.prob
r <- 1
newrow <- tPatients_ID
BCCL_kd.prob_ID <- insertRow(existingDF, newrow, r)
rownames(BCCL_kd.prob_ID) <- c("Deep_ID", rownameskdp)
```

#generation of mutImpact matrix
```{r}
#Generate pre_mutImpact matrix containing all CERES values and with IDs as colnames
pre_mutImpact <- BCCL_kd.ceres
colnames(pre_mutImpact)<-tPatients_ID

#generate empty mutImpact matrix
mutImpact <- matrix( , nrow = 17634, ncol = 28)
colnames(mutImpact)<-colnames(pre_mutImpact)
rownames(mutImpact)<-rownames(pre_mutImpact)

#fill mutImpact matrix with values
for (j in 1:ncol(pre_mutImpact)){
  lineID <- colnames(pre_mutImpact)[j] #select a column-name aka cell line
  for (i in 1:nrow(pre_mutImpact)){
    GOI <- rownames(pre_mutImpact)[i] #select a gene
    if (GOI %in% BCCL_Mutation[[lineID]]$Hugo_Symbol){
      mutImpact[i, j] <- pre_mutImpact[i, j]
    } else {
      mutImpact[i, j] <- NA
    }#replace CERES value with NA in case the gene is not mutated
  }
}
```
#generation of Input Matrix
```{r Input Matrix}
mutImpact_c = mutImpact[rowSums(is.na(mutImpact)) != ncol(mutImpact),]# remove all genes with all NA values
rownamesmutImpc = rownames(mutImpact_c)
mutImpact_c = cbind(rownamesmutImpc, mutImpact_c[,2:ncol(mutImpact_c)]) # insert new column with row names
dim(mutImpact_c) # check gene reduction 
rownameskdc2 = rownames(BCCL_kd.ceres)
BCCL_kd.ceres_2 = cbind(rownameskdc2, BCCL_kd.ceres[,2:ncol(BCCL_kd.ceres)]) # insert new column with row names
BCCL_kd.ceres_3 = BCCL_kd.ceres_2[BCCL_kd.ceres_2[,"rownameskdc2"] %in%  mutImpact_c[,"rownamesmutImpc"],] 
BCCL_kd.ceres_3 = BCCL_kd.ceres_3[,-c(1)]
BCCL_kd.ceres_3 = cbind(BCCL_kd.ceres_3, rowMeans(BCCL_kd.ceres_3)) #calculate rowmeans 
BCCL_kd.ceres_3 = BCCL_kd.ceres_3[rowMeans(BCCL_kd.ceres_3)<= 0,] # deletion of genes with CERES > 0

km_CERES= kmeans(x = BCCL_kd.ceres_3, centers = 4, nstart = 10)
data_cluster = km_CERES$cluster
rownames(data_cluster) = rownames(BCCL_kd.ceres_3)
data_clus_3 = BCCL_kd.ceres_3[data_cluster == 3,] # without driver mutation label 

drivermut =  c("ERBB2","MYCBP", "PARP10", "PIK3CA") # create vector with driver mutation names
data_clus_3e = data_clus_3
data_clus_3e["Driver mutation"] <- sapply(1:nrow(data_clus_3), function(j){
     if(rownames(data_clus_3e)[j] %in% drivermut){
         data_clus_3e[j,1] = "driver mutation"
     } else {
         data_clus_3e[j,1] = "no driver mutation"
     }
  }) # labeling driver mutations with "driver mutation" in data_clus_3e 

```


#find potential SSTs: Wilcoxon test
```{r}
driver_mut <- c("ERBB2","MYCBP", "PARP10", "PIK3CA") #enter driver mutations
mutImpact_r <- mutImpact[rowSums(is.na(mutImpact)) != ncol(mutImpact), ] #_r=reduced: get rid of all the ONLY NA rows (this will save computation)
mutImpact_kd.ceres <- BCCL_kd.ceres[rownames(BCCL_kd.ceres) %in% rownames(mutImpact_r),] # create matrix containing CERES scores of genes which are mutated once at minimum
colnames(mutImpact_kd.ceres) <- tPatients_ID 

testData <- lapply(seq_along(driver_mut), function(a) {
  driverMutPicker <- driver_mut[a] #pick a driver mutation
  driverMutData <- mutImpact_kd.ceres[driverMutPicker,] #get ceres scores of driver mutation
  
  outputData <- sapply(1:nrow(mutImpact_kd.ceres), function(b) {
    refGeneData <- mutImpact_kd.ceres[b,] #get ceres scores of reference gene (potential SST)
    
    if (rownames(refGeneData) != driverMutPicker) {
      out <- wilcox.test(as.numeric(driverMutData), as.numeric(refGeneData), paired = TRUE)$p.value #get p-value of wilcoxon signed-rank test
      out <- as.data.frame(out, rownames(mutImpact_r)[b]) 
      return(out)
    }
  })
  test = do.call(rbind, outputData)
  rownames(test) <- rownames(mutImpact_r)[which(rownames(mutImpact_r) != driverMutPicker)]
  return(test)
})
names(testData) <- driver_mut

lapply(testData, function(a) head(a)) #look at the data
```

#look for real SSTs based on Wilcoxon test data
```{r}
#get summary of distribution
summary(testData$ERBB2)
summary(testData$MYCBP)
summary(testData$PARP10)
summary(testData$PIK3CA)

#select 15 most promising SST candidates based on highest p-values - libraries needed: dplyr, tibble (included in "tidyverse")

SST_cand_ERBB2 <- as.data.frame(testData$ERBB2, col.names = names(testData$ERBB2)) #create new data frame containing testData for ERBB2
SST_cand_MYCBP <- as.data.frame(testData$MYCBP, col.names = names(testData$MYCBP))
SST_cand_PARP10 <- as.data.frame(testData$PARP10, col.names = names(testData$PARP10))
SST_cand_PIK3CA <- as.data.frame(testData$PIK3CA, col.names = names(testData$PIK3CA))

names(SST_cand_ERBB2) = "ERBB2" #rename column
names(SST_cand_MYCBP) = "MYCBP"
names(SST_cand_PARP10) = "PARP10"
names(SST_cand_PIK3CA) = "PIK3CA"

SST_cand_ERBB2 <- SST_cand_ERBB2 %>%rownames_to_column() %>% top_n(15, ERBB2) %>% column_to_rownames() #select 15 genes with highest p-value
SST_cand_MYCBP <- SST_cand_MYCBP %>% rownames_to_column() %>% top_n(15, MYCBP) %>% column_to_rownames()
SST_cand_PARP10 <- SST_cand_PARP10 %>% rownames_to_column() %>% top_n(15, PARP10) %>% column_to_rownames()
SST_cand_PIK3CA <- SST_cand_PIK3CA %>% rownames_to_column() %>% top_n(15, PIK3CA) %>% column_to_rownames()
```


