---
title: "MutImpactmatrix, k-means, Wilcoxon"
author: "Elias Benjamin Farr"
date: "17 Mai 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hello lisa :) 
Thank you for this warm welcome, Elias! :)

#requirements to run this code#
in order to run this you will need: BCCL_kd.ceres, tPatients_ID, BCCL_Mutation



#Generate pre_mutImpact matrix containing all CERES values and with IDs as colnames#
```{r} 
pre_mutImpact <- BCCL_kd.ceres
colnames(pre_mutImpact)<-tPatients_ID
```


#generate empty mutImpact matrix
```{r}
mutImpact <- matrix( , nrow = 17634, ncol = 28)
colnames(mutImpact)<-colnames(pre_mutImpact)
rownames(mutImpact)<-rownames(pre_mutImpact)
```

#fill mutImpact matrix with values
```{r}
for (j in 1:ncol(pre_mutImpact)){
  lineID <- colnames(pre_mutImpact)[j] #select a column-name aka cell line
  for (i in 1:nrow(pre_mutImpact)){
    GOI <- rownames(pre_mutImpact)[i] #select a gene
    if (GOI %in% BCCL_Mutation[[lineID]]$Hugo_Symbol){
      mutImpact[i, j] <- pre_mutImpact[i, j]
    } else {
      mutImpact[i, j] <- NA
    }#replace CERES value with NA in case the gene is not mutated
  }
}
```

##Paired Wilcoxon signed rank test

```{r}
#generate matrix of driver mutations
drivMat <- mutImpact[ , c(#colnr of DV)]

#generate 2nd vector of potential SSTS, i = gene
potSST <- as.vector(mutImpact[a, ])

#select driver mutation to find correspaonding SSTs
for i in (1:ncol(drivMat) function() {
  Dvm <- as.vector(drivMat[ ,i]
})

#suggested loop to design Wilcoxon matrix
wlxmat <- lapply(1:nrow(mutImpact), function(a) {
  potSST <- as.vector(mutImpact[a, ])
  wilcox.test(Dvm, potSST, paired = TRUE, na.action = na.exclude)
})
#returns error:  Error in wilcox.test.default(Dvm, potSST, paired = TRUE, na.action = na.exclude) : 
  #not enough (finite) 'x' observations 
```