---
title: "PCA and related plots -> Dmut"
author: "Elias Benjamin Farr"
date: "17 Mai 2019"
output: html_document
---
First test PCA
```{r PCA.packages.install}
install.packages("remotes")
remotes::install_github("vqv/ggbiplot")
install.packages("scales")
install.packages("grid")
insall.packages("plyr")
```

PCA but not yet complete!
``` {r PCA}
tBCCL_Expression = t(BCCL_Expression)
Expression.pca = prcomp(tBCCL_Expression, center = F, scale. = F)  # centering and scaling of data not possible since row of zeros cannot be scaled down to varianz 1 due to the "AARSP1" column consisting only of zeros
#cleaning matrix of AARSP1 column
rmv_AARSP1 = which(colnames(tBCCL_Expression) %in% c("AARSP1")) 
cl_tBCCL_Expression = data[, -rmv_AARSP1] 

summary(Expression.pca)
Expression.pca
plot(Expression.pca, type = "l")  # First two componets explain most of the variability in the data
plot(Expression.pca$rotation[, 1], Expression.pca$rotation[, 2],pch = 19, xlab = "PC1", ylab = "PC2") 
```
From first analysis visible that PC1 and PC2 contribute to greatest variability of data set!


Visualising PCA with ggbiplot and ggplot2 package- does not work yet 
```{r nicer.visualisation}
library(ggbiplot) #doesn't work yet
g = ggbiplot(Expression.pca, obs.scale = 1, var.scale = 1,  groups = wine.class, ellipse = TRUE, circle = TRUE)
g = g + scale_color_discrete(name = '') 
g = g + theme(legend.direction = 'horizontal', legend.position = 'top')
g
```

